server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri:       # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                          # Git仓库的密码
          health:
            repositories:
              a-foo:
                label: 2
                name: microservice-foo
                profiles: dev
    bus:
      trace:
        enabled: true


encrypt:
#对称加密秘钥
  #key: idea
#非对称加密
  key-store:
    location: classpath:/server.jks
    password: letmein    #storepass
    alias: mytestkey
    secret: changeme    #keypass
