server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/,http://admin:admin123@localhost:8762/eureka/
  instance:
    prefer-ip-address: true
zuul:
  #禁用自带的过滤器
  sendResponseFilter:
    post:
      disable: true
 # ignored-services: microservice-provider-user,microservice-consumer-movie