server:
  port: 8081
spring:
  application:
    name: microservice-consumer-movie
eureka:
  client:
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/,http://admin:admin123@localhost:8762/eureka/
  instance:
    prefer-ip-address: true

#配置文件设置，负载均衡的方式，跟RibbonConfiguration效果一样
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
        enabled:true
  compression:
    request:
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
        enable:true

logging:
  level:
   springcloud.microserviceconsumermovie.fegin.UserFeginClient: DEBUG # 将Feign接口的日志级别设置成DEBUG，因为Feign的Logger.Level只对DEBUG作出响应。

management:
  security:
    enabled: false



